# Generated by Django 3.2.6 on 2022-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=1000)),
                ('phone', models.IntegerField()),
                ('state', models.CharField(choices=[('state', 'State'), ('river', 'Rivers')], max_length=40)),
                ('location', models.CharField(choices=[('geographical location', 'Geographical Location'), ('eleme', 'Eleme'), ('bolo', 'Bolo'), ('etche', 'Etche'), ('ikwere', 'Ikwere'), ('obio-akpor', 'Obio-Akpor'), ('oyigbo', 'Oyigbo'), ('okrika', 'Okrika')], max_length=40)),
                ('houses', models.CharField(choices=[('mini_flats', 'Mini_Flats'), ('ware_house', 'Ware_House'), ('plots_&_land', 'Plots_&_Land'), ('duplex', 'Duplex'), ('office_space', 'Office_Space'), ('terraced_bungalow', 'Terraced_Bungalow'), ('houses', 'House')], max_length=40)),
                ('describe', models.CharField(max_length=64)),
            ],
        ),
    ]
